### PR TITLE
feat: add macos bundle

### PR DESCRIPTION
**Pull request by thecaralice**

### CODE REVIEW

**Comment by thecaralice** [comment]
I thought Google has nothing to do with this project? Nevermind then.

**Comment by marienz** [comment]
Sorry to hear that!

...this is going to sound like I'm arguing, which is not the intent. It's your code, you get to decide what's done with it. But I do want to give my side on the "Google"-ness of this project, in case anyone else stumbles across this issue:

tl;dr I work for Google, Google insists I put that CLA bot up, that's it, that's Google's only involvement in this project.

Long version:

- I'm employed by Google, but Google does not pay me to work on this (I work on it in my spare time). Google does not influence the code that went into this project.
- For reasons I don't understand, Google likes to keep copyright for the code *I* have written. If I'd wanted to own the copyright, I was told there'd be extra hoops to jump through/more review/etc: I was lazy, so I went for the path that promised to be easiest. Google is fine with me releasing this under an open source license, and you can do whatever's allowed by that license. (https://opensource.google/documentation/reference/releasing lists the options I was given.)
- For reasons I understand even less, Google's internal documentation says I need to get contributors to sign a CLA. https://opensource.google/documentation/reference/releasing/contributions is supposed to be an external copy of the same documentation, and currently says I don't need to: I'm following up on that and will remove the bot if it turns out the external documentation is correct.
- That CLA does *not* (to the best of my understanding, I'm not a lawyer, but see also https://opensource.google/documentation/reference/cla for Google's take) ask you to transfer ownership/copyright of *your* code to Google. You don't lose rights over your code, but you sign a thing that confirms it really is your code and that you're ok with Google redistributing it.
  - If I wasn't forced to have that CLA bot, I would also assume it's your code and that you're ok with me redistributing it (under the Apache license this project uses) , because otherwise why would you send the PR...  I just wouldn't ask every individual contributor to sign some kind of formal statement about it.
  - Why does Google insist on that CLA if they're not doing the redistributing, I am? I don't know!
  - Why does the CLA bot say this is "a Google open source project"? I assume that's "just" a bad message (the bot doesn't distinguish between side projects like mine and official Google projects). If I have to keep the bot, I'll see if I can get that improved: having to stick a "not a Google product" disclaimer (see https://opensource.google/documentation/reference/releasing/publishing#disclaimer) on here and then also having a bot proclaim this is a "Google open source project" is... more than a little confusing. Nor is there a "we" when the bot says "Before we can look at your pull request", it's just me here.

I'll update this PR again if I can remove the CLA bot, in case your problem is the CLA and not who employs me.

If not, sorry for the hassle of having to maintain your own fork :(

**Comment by thecaralice** [comment]
While I understand the motivation behind having a CLA, I do not like the idea of having to provide a Google account. I also attempted creating a fresh account to use for Google CLA only, but Google expects confidential information I would prefer not to disclose like my phone number. Going to try using a temporary phone number service perhaps.

**Comment by thecaralice** [comment]
> trip some anti-abuse rules / set up accounts from IP addresses that look "weird"

I am a Russian resident, so I have extra weirdness points on that. Moreover, TIL Google stopped sending verification messages to Russian numbers. Nevertheless, I was able to create an account and sign the agreement right before I reopened this PR.

**Comment by marienz** [comment]
> Nevertheless, I was able to create an account and sign the agreement right before I reopened this PR.

So you did (I missed the check status changing).

If I understand correctly the quoting you're adding is not necessary, as they're all store-relative paths and Nix doesn't allow whitespace (or other characters problematic to shell) in them. But no harm in adding quotes, if only because it appeases shellcheck and similar tools that don't know it's safe without them.

Passes CI, so will merge. Thanks for fixing this (and wrangling the CLA bot)!

(I'll separately look into running CI on GitHub's MacOS workers: I'd expect that to run the code you're adding but it wouldn't actually ensure the bundle works without further effort... seems lower-priority)

**Comment by thecaralice** [comment]
> If I understand correctly the quoting you're adding is not necessary, as they're all store-relative paths and Nix doesn't allow whitespace (or other characters problematic to shell) in them. But no harm in adding quotes, if only because it appeases shellcheck and similar tools that don't know it's safe without them.

Well, it's safer to simply always quote as a rule of thumb. Moreover, with alternative Nix implementations now in play, there might soon exist cases of store paths not being in `/nix/store/`.

> (I'll separately look into running CI on GitHub's MacOS workers: I'd expect that to run the code you're adding but it wouldn't actually ensure the bundle works without further effort... seems lower-priority)

That's pretty doable. I have a [flake-parts module](https://github.com/thecaralice/flake-gha) I made when I needed easier GitHub Actions configuration, which is not at its best but it works.


Also, I forgot to update README which still says there's no macOS bundle support yet.

**Comment by marienz** [comment]
> Moreover, with alternative Nix implementations now in play, there might soon exist cases of store paths not being in /nix/store/.

Turns out I was wrong about Nix rejecting this, but nixpkgs fails about as early as it's possible to (assuming I'm holding things right, see https://nix.dev/manual/nix/2.20/store/types/local-store)

```
> nix build --store 'local?store=/tmp/my nix/store&state=/tmp/my nix/state&log=/tmp/my nix/log' nixpkgs#hello
...
error: builder for '/tmp/my nix/store/49kd4xii62krnbjw7l57ll06lx503hhv-bootstrap-tools.drv' failed with exit code 127;
       last 2 log lines:
       > Unpacking the bootstrap tools...
       > /tmp/my nix/store/0zahwiyji8qdrswh0hpm7ryg2hffqr63-unpack-bootstrap-tools.sh: line 3: /tmp/my: not found
       For full logs, run 'nix log /tmp/my nix/store/49kd4xii62krnbjw7l57ll06lx503hhv-bootstrap-tools.drv'.
```

https://github.com/NixOS/nixpkgs/blob/03b6d7f18323bb6b4b41ea2272c245772caefee3/pkgs/stdenv/linux/bootstrap-tools/glibc/unpack-bootstrap-tools.sh#L3 doesn't quote `$builder` (which is `"/tmp/my nix/store/hz2wslsarq93k06y0q58wfngi463q2xd-busybox"`). That's not the only spot, nixpkgs pretty routinely uses things like `$out` without quoting.

So Nix supports this more than I thought it did, but you might have to leave nixpkgs behind...

> CI on GitHub's MacOS workers

Last time I tried CI on MacOS the tests failed (https://github.com/marienz/nix-doom-emacs-unstraightened/actions/runs/9624008325, the logs have been garbage-collected but if I recall correctly things built but my tests didn't execute correctly). I'll give that another go once I've dealt with the current CI failure (triggered by a nixpkgs change, haven't tracked it down yet)...

**Comment by marienz** [comment]
Figured out the CI issue (https://github.com/marienz/nix-doom-emacs-unstraightened/commit/b41fd0f6af008ad6607af23d78b3c65e9db946ce, obvious in hindsight), so I went ahead and updated the README to state macOS works. Thanks again!

(...also, CI went red again but that'll be https://github.com/doomemacs/doomemacs/commit/8cafbe4408e7d6c68947a2066e5837379d0983c1, haven't started looking yet but hopefully it just moved things around...)

**Comment by marienz** [comment]
(Much belated update on the [CLA situation](https://github.com/marienz/nix-doom-emacs-unstraightened/pull/36#issuecomment-2447199735): [Google waived copyright](https://opensource.google/documentation/reference/releasing#iarc) on my contributions, which means I've removed the bot (or at least I tried, we'll see on the next PR...)).

**Pull request merged**
